repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
    -   id: docformatter
        args: [--wrap-summaries, '100', --wrap-description,'100', --in-place]
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.0
    hooks:
    -   id: ruff-format
    -   id: ruff
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
      - id: mypy
        args: [
          --ignore-missing-imports,
          --disallow-untyped-calls,
          --disallow-untyped-defs,
          --disallow-incomplete-defs,
          --check-untyped-defs,
          --no-implicit-optional,
          --show-error-codes
        ]
