name: versa-dev
channels:
  - defaults
dependencies:
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - certifi=2024.7.4
  - cffi=1.16.0
  - cryptography=42.0.5
  - freetype=2.12.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - huggingface_hub=0.23.1
  - idna=3.7
  - importlib-metadata=7.0.1
  - iniconfig=1.1.1
  - jinja2=3.1.4
  - jpeg=9e
  - lcms2=2.12
  - lerc=3.0
  - libcxx=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libjpeg-turbo=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - networkx=3.3
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.4.0
  - openssl=3.0.14
  - pillow=10.3.0
  - pip=24.0
  - pluggy=1.0.0
  - pycparser=2.21
  - pysocks=1.7.1
  - pytest=7.4.4
  - python=3.11.9
  - pyyaml=6.0.1
  - readline=8.2
  - setuptools=69.5.1
  - sqlite=3.45.3
  - sympy=1.12
  - tk=8.6.14
  - tqdm=4.66.4
  - typing_extensions=4.11.0
  - urllib3=2.2.2
  - wheel=0.43.0
  - xz=5.4.6
  - yaml=0.2.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - accelerate==0.32.1
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - altair==5.3.0
      - annotated-types==0.7.0
      - anyio==4.4.0
      - appnope==0.1.4
      - asttokens==2.4.1
      - astunparse==1.6.3
      - attrs==23.2.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.3
      - bitarray==2.9.2
      - bitsandbytes==0.40.2
      - black==24.4.2
      - bleach==6.1.0
      - blinker==1.8.2
      - cachetools==5.3.3
      - catalogue==2.0.10
      - cfgv==3.4.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colbert-ai==0.2.19
      - coloredlogs==15.0.1
      - dataclasses-json==0.6.7
      - datasets==2.20.0
      - decorator==5.1.1
      - defusedxml==0.7.1
      - deprecated==1.2.14
      - dill==0.3.8
      - dirtyjson==1.0.8
      - distlib==0.3.8
      - distro==1.9.0
      - docopt==0.6.2
      - duckduckgo-search==6.2.6
      - einops==0.8.0
      - et-xmlfile==1.1.0
      - executing==2.0.1
      - faiss-cpu==1.8.0.post1
      - fast-pytorch-kmeans==0.2.0.1
      - fastjsonschema==2.20.0
      - filelock==3.15.4
      - flask==3.0.3
      - flatbuffers==24.3.25
      - frozenlist==1.4.1
      - fsspec==2024.5.0
      - gast==0.6.0
      - git-python==1.0.3
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-pasta==0.2.0
      - greenlet==3.0.3
      - grpcio==1.64.1
      - h11==0.14.0
      - h5py==3.11.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.23.4
      - humanfriendly==10.0
      - identify==2.6.0
      - ipython==8.12.3
      - itsdangerous==2.2.0
      - jedi==0.19.1
      - joblib==1.4.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - jupyterlab-pygments==0.3.0
      - keras==3.4.1
      - langchain==0.2.10
      - langchain-community==0.2.7
      - langchain-core==0.2.22
      - langchain-huggingface==0.0.3
      - langchain-text-splitters==0.2.2
      - langsmith==0.1.83
      - libclang==18.1.1
      - llama-cloud==0.0.6
      - llama-index==0.10.53
      - llama-index-agent-openai==0.2.8
      - llama-index-cli==0.1.12
      - llama-index-core==0.10.53.post1
      - llama-index-embeddings-openai==0.1.10
      - llama-index-indices-managed-llama-cloud==0.2.3
      - llama-index-legacy==0.9.48
      - llama-index-llms-openai==0.1.25
      - llama-index-multi-modal-llms-openai==0.1.7
      - llama-index-program-openai==0.1.6
      - llama-index-question-gen-openai==0.1.3
      - llama-index-readers-file==0.1.29
      - llama-index-readers-llama-parse==0.1.6
      - llama-parse==0.4.6
      - markdown==3.6
      - markdown-it-py==3.0.0
      - marshmallow==3.21.3
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.0.2
      - ml-dtypes==0.3.2
      - mlx==0.16.0
      - mlx-lm==0.16.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - mypy-extensions==1.0.0
      - namex==0.0.8
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - ninja==1.11.1.1
      - nltk==3.8.1
      - nodeenv==1.9.1
      - onnx==1.16.1
      - openai==1.35.11
      - openpyxl==3.1.5
      - opt-einsum==3.3.0
      - optimum==1.21.2
      - optree==0.12.1
      - orjson==3.10.6
      - packaging==23.2
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pathspec==0.12.1
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pipreqs==0.5.0
      - platformdirs==4.2.2
      - pre-commit==3.7.1
      - primp==0.5.5
      - prompt-toolkit==3.0.47
      - protobuf==4.25.3
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==16.1.0
      - pyarrow-hotfix==0.6
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pydeck==0.9.1
      - pygments==2.18.0
      - pynvml==11.5.0
      - pypdf==4.2.0
      - pypdf2==3.0.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2024.1
      - pyzmq==26.1.1
      - referencing==0.35.1
      - regex==2024.5.15
      - requests==2.32.3
      - rich==13.7.1
      - rpds-py==0.19.0
      - ruff==0.5.5
      - safetensors==0.4.3
      - scikit-learn==1.5.1
      - scipy==1.14.0
      - sentence-transformers==2.7.0
      - sentencepiece==0.2.0
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.5
      - sqlalchemy==2.0.31
      - srsly==2.4.8
      - stack-data==0.6.3
      - streamlit==1.36.0
      - striprtf==0.0.26
      - tenacity==8.4.2
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.16.2
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-macos==2.16.2
      - tensorflow-metal==1.1.0
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - tiktoken==0.7.0
      - tinycss2==1.3.0
      - tokenizers==0.19.1
      - toml==0.10.2
      - toolz==0.12.1
      - torch==2.3.1
      - torchaudio~=2.3.0
      - torchvision==0.18.1
      - tornado==6.4.1
      - traitlets==5.14.3
      - transformers~=4.42.2
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - tzdata==2024.1
      - ujson==5.10.0
      - virtualenv==20.26.3
      - voyager==2.0.6
      - watchdog==4.0.1
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - werkzeug==3.0.3
      - wrapt==1.16.0
      - xxhash==3.4.1
      - yarg==0.1.9
      - yarl==1.9.4
