# Everything in this section will be available as an environment variable
ACCESS_TOKEN = "gAAAAABmzXFge5myN7JiYwRML0wlOMHJeyn94Jar0RUv3WxyLako_jYa41AwOFxu3uOGPTfOjgH6oNuyGPH0NA8zZL4G8SNCXPThyBnsDI_o8TtsgM2f7ILfb8ksgGxN7kvdaskeYoPj"
KEY = 'Wp2vo_8sqKJ4Sy81IjjGWy-gt4hLkKVmb_X-ubeTImI='
